AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sentinel Storage Components - S3 Buckets and DynamoDB Tables'

Parameters:
  ProjectName:
    Type: String
    Default: sentinel
  Environment:
    Type: String
    Default: dev
  ContentRetentionDays:
    Type: Number
    Default: 365
  DynamoDBBillingMode:
    Type: String
    Default: PAY_PER_REQUEST
    AllowedValues: [PAY_PER_REQUEST, PROVISIONED]
  KMSKeyArn:
    Type: String
    Description: ARN of KMS key for encryption
  RandomSuffix:
    Type: String
    Description: Random suffix for unique resource naming

Resources:
  # S3 Buckets for Storage
  ContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${Environment}-content-${RandomSuffix}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref KMSKeyArn
            BucketKeyEnabled: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ContentLifecycle
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
            ExpirationInDays: !Ref ContentRetentionDays
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-content-bucket'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${Environment}-artifacts-${RandomSuffix}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref KMSKeyArn
            BucketKeyEnabled: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ArtifactsLifecycle
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
            ExpirationInDays: 365
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-artifacts-bucket'

  TracesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${Environment}-traces-${RandomSuffix}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref KMSKeyArn
            BucketKeyEnabled: true
      LifecycleConfiguration:
        Rules:
          - Id: TracesLifecycle
            Status: Enabled
            Transitions:
              - TransitionInDays: 7
                StorageClass: STANDARD_IA
            ExpirationInDays: 90
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-traces-bucket'

  # DynamoDB Tables
  ArticlesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-${Environment}-articles'
      BillingMode: !Ref DynamoDBBillingMode
      AttributeDefinitions:
        - AttributeName: article_id
          AttributeType: S
        - AttributeName: state
          AttributeType: S
        - AttributeName: published_at
          AttributeType: S
        - AttributeName: cluster_id
          AttributeType: S
        - AttributeName: source
          AttributeType: S
      KeySchema:
        - AttributeName: article_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: state-published_at-index
          KeySchema:
            - AttributeName: state
              KeyType: HASH
            - AttributeName: published_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          BillingMode: !Ref DynamoDBBillingMode
        - IndexName: cluster-published_at-index
          KeySchema:
            - AttributeName: cluster_id
              KeyType: HASH
            - AttributeName: published_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          BillingMode: !Ref DynamoDBBillingMode
        - IndexName: source-published_at-index
          KeySchema:
            - AttributeName: source
              KeyType: HASH
            - AttributeName: published_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          BillingMode: !Ref DynamoDBBillingMode
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !Ref KMSKeyArn
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-articles-table'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  CommentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-${Environment}-comments'
      BillingMode: !Ref DynamoDBBillingMode
      AttributeDefinitions:
        - AttributeName: comment_id
          AttributeType: S
        - AttributeName: article_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
        - AttributeName: parent_comment_id
          AttributeType: S
      KeySchema:
        - AttributeName: comment_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: article-created_at-index
          KeySchema:
            - AttributeName: article_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          BillingMode: !Ref DynamoDBBillingMode
        - IndexName: parent-created_at-index
          KeySchema:
            - AttributeName: parent_comment_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          BillingMode: !Ref DynamoDBBillingMode
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !Ref KMSKeyArn
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-comments-table'

  MemoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-${Environment}-memory'
      BillingMode: !Ref DynamoDBBillingMode
      AttributeDefinitions:
        - AttributeName: memory_id
          AttributeType: S
        - AttributeName: memory_type
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
        - AttributeName: session_id
          AttributeType: S
      KeySchema:
        - AttributeName: memory_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: type-created_at-index
          KeySchema:
            - AttributeName: memory_type
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          BillingMode: !Ref DynamoDBBillingMode
        - IndexName: session-created_at-index
          KeySchema:
            - AttributeName: session_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          BillingMode: !Ref DynamoDBBillingMode
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !Ref KMSKeyArn
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-memory-table'

Outputs:
  ContentBucketName:
    Description: Name of the content S3 bucket
    Value: !Ref ContentBucket
    Export:
      Name: !Sub '${ProjectName}-${Environment}-content-bucket-name'
  
  ContentBucketArn:
    Description: ARN of the content S3 bucket
    Value: !GetAtt ContentBucket.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-content-bucket-arn'
  
  ArtifactsBucketName:
    Description: Name of the artifacts S3 bucket
    Value: !Ref ArtifactsBucket
    Export:
      Name: !Sub '${ProjectName}-${Environment}-artifacts-bucket-name'
  
  ArtifactsBucketArn:
    Description: ARN of the artifacts S3 bucket
    Value: !GetAtt ArtifactsBucket.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-artifacts-bucket-arn'
  
  TracesBucketName:
    Description: Name of the traces S3 bucket
    Value: !Ref TracesBucket
    Export:
      Name: !Sub '${ProjectName}-${Environment}-traces-bucket-name'
  
  TracesBucketArn:
    Description: ARN of the traces S3 bucket
    Value: !GetAtt TracesBucket.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-traces-bucket-arn'
  
  ArticlesTableName:
    Description: Name of the articles DynamoDB table
    Value: !Ref ArticlesTable
    Export:
      Name: !Sub '${ProjectName}-${Environment}-articles-table-name'
  
  ArticlesTableArn:
    Description: ARN of the articles DynamoDB table
    Value: !GetAtt ArticlesTable.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-articles-table-arn'
  
  CommentsTableName:
    Description: Name of the comments DynamoDB table
    Value: !Ref CommentsTable
    Export:
      Name: !Sub '${ProjectName}-${Environment}-comments-table-name'
  
  CommentsTableArn:
    Description: ARN of the comments DynamoDB table
    Value: !GetAtt CommentsTable.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-comments-table-arn'
  
  MemoryTableName:
    Description: Name of the memory DynamoDB table
    Value: !Ref MemoryTable
    Export:
      Name: !Sub '${ProjectName}-${Environment}-memory-table-name'
  
  MemoryTableArn:
    Description: ARN of the memory DynamoDB table
    Value: !GetAtt MemoryTable.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-memory-table-arn'